name: 'Merge two branches and force push'

description: Merge one branch into another & force push
inputs:
  source_branch:
    description: Branch name to pull from, default is triggered branch
    required: false
  destination_branch:
    description: Branch name merge into in this repo
    required: true
  github_token:
    description: GitHub token secret
    required: true
runs:
  using: composite
  steps:
    - name: merge ${{ inputs.source_branch }} into ${{ inputs.destination_branch }}
      shell: bash
      run: |
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "Set the GITHUB_TOKEN environment variable."
          exit 1
        fi

        if [ ! -z "$SOURCE_BRANCH" ]; then
          SOURCE_BRANCH="$SOURCE_BRANCH"
        elif [ ! -z "$GITHUB_REF_NAME" ]; then
          SOURCE_BRANCH="$GITHUB_REF_NAME"
        else
          echo "Set the SOURCE_BRANCH environment variable or trigger from a branch."
          exit 1
        fi

        # Workaround for `hub` auth error https://github.com/github/hub/issues/2149#issuecomment-513214342
        export GITHUB_USER="$GITHUB_ACTOR"

        git config --global user.email "$GITHUB_ACTOR"
        git config --global user.name "$GITHUB_ACTOR"
        git config --global pull.ff only

        git clone "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY" repo
        git fetch
        cd repo
        git checkout $SOURCE_BRANCH
        git pull
        git push
        git checkout $DESTINATION_BRANCH
        git pull
        git push
        git merge $SOURCE_BRANCH
        # git add -A
        # git commit -m "update $DESTINATION_BRANCH"
        git push --force
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        SOURCE_BRANCH: ${{ inputs.source_branch }}
        DESTINATION_BRANCH: ${{ inputs.destination_branch }}
